"""
Provision the Grafana SQLite data source AND the capstone dashboard.

Two modes:
  1. Bundled (preferred): a sibling ``grafana/`` folder exists next to the
     watcher (the portable Grafana shipped to the client).
  2. System: fall back to whatever ``grafana-cli`` resolves on PATH.

Idempotent — safe to re-run.
"""
import pathlib
import shutil
import sys
import textwrap

ROOT = pathlib.Path(__file__).resolve().parent.parent
DB_PATH = ROOT / "capstone.db"
DASHBOARD_SRC = ROOT / "grafana" / "dashboard.json"


def find_grafana_home() -> pathlib.Path | None:
    bundled = ROOT / "grafana"
    # Bundled portable Grafana ships its server binary under bin/
    if (bundled / "bin" / "grafana-server.exe").exists() or (bundled / "bin" / "grafana-server").exists():
        return bundled
    cli = shutil.which("grafana-cli")
    if cli:
        return pathlib.Path(cli).resolve().parent.parent
    return None


def write_server_config(grafana_home: pathlib.Path) -> pathlib.Path:
    """Bind Grafana to all interfaces so other PCs on the LAN can reach it."""
    conf_dir = grafana_home / "conf"
    conf_dir.mkdir(parents=True, exist_ok=True)
    ini = textwrap.dedent("""\
        # Generated by provision.py — overrides defaults.ini for LAN access.
        [server]
        protocol = http
        http_addr = 0.0.0.0
        http_port = 3000

        [users]
        # Admin invites/creates accounts; staff cannot self-register.
        allow_sign_up = false
        # New users invited by admin default to Viewer (read-only).
        auto_assign_org_role = Viewer

        [auth.anonymous]
        enabled = false
    """)
    target = conf_dir / "custom.ini"
    target.write_text(ini, encoding="utf-8")
    return target


def write_datasource(grafana_home: pathlib.Path) -> pathlib.Path:
    prov_dir = grafana_home / "conf" / "provisioning" / "datasources"
    prov_dir.mkdir(parents=True, exist_ok=True)
    yaml = textwrap.dedent(f"""\
        apiVersion: 1

        datasources:
          - name: Capstone SQLite
            uid: capstone-sqlite
            type: frser-sqlite-datasource
            access: proxy
            isDefault: true
            jsonData:
              path: {DB_PATH.as_posix()}
    """)
    target = prov_dir / "capstone-sqlite.yaml"
    target.write_text(yaml, encoding="utf-8")
    return target


def write_dashboard(grafana_home: pathlib.Path) -> pathlib.Path | None:
    if not DASHBOARD_SRC.exists():
        return None
    prov_dir = grafana_home / "conf" / "provisioning" / "dashboards"
    prov_dir.mkdir(parents=True, exist_ok=True)
    dash_dir = grafana_home / "conf" / "provisioning" / "dashboard-files"
    dash_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(DASHBOARD_SRC, dash_dir / "capstone.json")

    yaml = textwrap.dedent(f"""\
        apiVersion: 1

        providers:
          - name: Capstone
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            updateIntervalSeconds: 30
            allowUiUpdates: true
            options:
              path: {(dash_dir).as_posix()}
    """)
    target = prov_dir / "capstone-dashboards.yaml"
    target.write_text(yaml, encoding="utf-8")
    return target


def main() -> int:
    home = find_grafana_home()
    if not home:
        print("ERROR: Could not locate Grafana.")
        print("  - Bundled mode: expected a 'grafana/' folder next to this watcher.")
        print("  - System mode: 'grafana-cli' not found on PATH.")
        return 1

    try:
        cfg = write_server_config(home)
        print(f"Wrote server config: {cfg}")
        ds = write_datasource(home)
        print(f"Wrote data source: {ds}")
        print(f"  -> SQLite DB: {DB_PATH}")
    except PermissionError:
        print(f"ERROR: cannot write to {home}. Re-run as Administrator.")
        return 1

    dash = write_dashboard(home)
    if dash:
        print(f"Wrote dashboard provider: {dash}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
